package words

import "strings"

// CommonWords contains the 1000 most common English words (British English)
// All words are lowercase only
var CommonWords = []string{
	"the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
	"it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
	"this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
	"or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
	"so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
	"when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
	"people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
	"than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
	"back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
	"even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
	"is", "was", "are", "been", "has", "had", "were", "said", "each", "she",
	"may", "find", "long", "down", "did", "get", "made", "before", "might", "many",
	"write", "must", "water", "word", "such", "call", "side", "where", "help", "through",
	"much", "still", "same", "while", "great", "last", "small", "own", "found", "those",
	"never", "show", "under", "little", "every", "house", "world", "put", "old", "being",
	"once", "went", "next", "hand", "high", "off", "end", "live", "night", "school",
	"another", "away", "home", "something", "need", "study", "keep", "might", "point", "start",
	"head", "story", "city", "play", "spell", "young", "few", "enough", "always", "watch",
	"three", "letter", "until", "far", "children", "got", "walk", "example", "ease", "paper",
	"always", "music", "often", "run", "late", "hard", "set", "food", "both", "between",
	"name", "line", "right", "boy", "soon", "grow", "state", "left", "near", "kind",
	"together", "thought", "father", "mother", "white", "seem", "began", "country", "family", "fact",
	"earth", "part", "place", "life", "open", "read", "north", "south", "change", "question",
	"tell", "turn", "move", "sea", "light", "self", "face", "number", "group", "idea",
	"woman", "bring", "book", "problem", "better", "learn", "ask", "should", "britain", "plant",
	"above", "girl", "sometimes", "without", "stop", "four", "second", "later", "programme", "order",
	"man", "men", "woman", "women", "money", "eye", "thing", "room", "feel", "since",
	"area", "today", "already", "during", "minute", "morning", "within", "hear", "moment", "body",
	"close", "nothing", "certain", "along", "stand", "against", "government", "system", "car", "power",
	"company", "believe", "hold", "week", "person", "case", "service", "become", "possible", "mind",
	"however", "member", "pay", "law", "meet", "month", "true", "door", "early", "course",
	"real", "continue", "nice", "public", "include", "whether", "big", "half", "sure", "reason",
	"free", "black", "though", "level", "view", "important", "using", "centre", "best", "sense",
	"across", "business", "known", "working", "study", "health", "result", "development", "national", "social",
	"least", "whole", "support", "war", "control", "child", "given", "red", "present", "table",
	"market", "office", "action", "care", "perhaps", "perhaps", "window", "report", "decide", "building",
	"death", "yes", "behind", "reach", "local", "couple", "job", "position", "produce", "effect",
	"political", "interest", "five", "ago", "history", "land", "different", "economic", "international", "process",
	"voice", "art", "finally", "cost", "strong", "plan", "party", "available", "full", "class",
	"base", "common", "information", "research", "human", "love", "story", "court", "air", "record",
	"happen", "provide", "friend", "several", "field", "role", "appear", "age", "street", "likely",
	"police", "technology", "future", "inside", "paper", "clear", "special", "front", "rate", "value",
	"language", "among", "stay", "six", "period", "policy", "computer", "million", "rather", "create",
	"tax", "similar", "relationship", "personal", "single", "return", "experience", "form", "price", "british",
	"image", "accept", "doctor", "require", "type", "military", "agree", "actually", "theory", "step",
	"choose", "foreign", "involve", "hospital", "usually", "cause", "student", "private", "news", "game",
	"offer", "degree", "term", "material", "able", "low", "performance", "either", "cover", "behaviour",
	"energy", "building", "piece", "address", "describe", "player", "third", "current", "expect", "design",
	"training", "model", "team", "staff", "risk", "choice", "individual", "wrong", "data", "range",
	"simple", "activity", "film", "bit", "particular", "test", "size", "consider", "site", "pass",
	"star", "argue", "measure", "specific", "management", "direction", "indeed", "cut", "sign", "population",
	"director", "suddenly", "recently", "analysis", "project", "effort", "method", "physical", "discussion", "evidence",
	"major", "stock", "whatever", "opportunity", "scene", "environment", "practice", "financial", "season", "science",
	"music", "pressure", "natural", "treatment", "section", "college", "reduce", "response", "concern", "ten",
	"activity", "traditional", "budget", "culture", "amount", "seven", "growth", "figure", "factor", "success",
	"general", "responsibility", "subject", "role", "allow", "beyond", "deal", "rest", "community", "society",
	"recent", "article", "conference", "standard", "quickly", "interview", "character", "break", "resource", "approach",
	"eight", "increase", "strategy", "statement", "structure", "surface", "movement", "short", "add", "nature",
	"legal", "product", "medical", "situation", "whose", "event", "poor", "author", "reality", "anyone",
	"although", "expert", "ready", "final", "series", "production", "speech", "leader", "board", "drug",
	"unit", "election", "worker", "condition", "beautiful", "peace", "century", "trade", "attention", "nine",
	"education", "property", "detail", "goal", "attack", "operation", "skill", "picture", "station", "loss",
	"manager", "trouble", "brother", "summer", "campaign", "focus", "everything", "benefit", "everyone", "trial",
	"cell", "religious", "network", "apply", "audience", "knowledge", "memory", "administration", "bank", "purpose",
	"benefit", "protect", "coach", "forward", "security", "feeling", "capital", "everything", "challenge", "race",
	"fill", "share", "access", "artist", "debate", "quality", "chance", "feature", "agency", "difference",
	"central", "pull", "note", "establish", "explain", "identify", "organisation", "hair", "notice", "crime",
	"hot", "arm", "travel", "total", "average", "democratic", "space", "follow", "pattern", "professor",
	"weight", "marriage", "dead", "list", "senior", "affect", "professional", "hotel", "maintain", "miss",
	"kitchen", "blue", "wonder", "represent", "tree", "contain", "heart", "various", "ball", "green",
	"dark", "eat", "doctor", "colour", "stage", "shot", "trouble", "animal", "region", "assume",
	"develop", "popular", "collection", "fund", "drop", "perform", "hit", "bed", "remain", "original",
	"floor", "official", "deep", "foot", "carry", "pain", "behaviour", "determine", "fight", "success",
	"bottom", "basic", "civil", "cultural", "safe", "degree", "garden", "necessary", "claim", "complete",
	"account", "seek", "district", "generation", "threat", "exist", "employee", "exactly", "charge", "draw",
	"institution", "candidate", "former", "entire", "technology", "participate", "rule", "enter", "science", "disease",
	"tend", "effort", "date", "potential", "sport", "replace", "source", "edge", "card", "wide",
	"movement", "release", "fear", "prepare", "smile", "material", "oil", "modern", "cry", "rich",
	"dream", "former", "finger", "stuff", "imagine", "glass", "defence", "corner", "nearly", "impact",
	"wall", "video", "basic", "express", "conference", "independent", "appropriate", "western", "hang", "opinion",
	"promise", "save", "trouble", "mention", "drive", "wind", "tiny", "seat", "critical", "item",
	"decade", "pretty", "realise", "rise", "yard", "refer", "stone", "reflect", "limited", "huge",
	"connection", "count", "associate", "style", "extend", "absolutely", "damage", "variety", "spring", "complex",
	"truth", "collect", "commission", "executive", "recognise", "reform", "category", "significant", "citizen", "majority",
	"serve", "magazine", "demand", "prove", "content", "financial", "magazine", "dinner", "hotel", "lack",
	"spot", "reform", "track", "press", "ticket", "sleep", "train", "fly", "sell", "store",
	"influence", "teach", "mouth", "immediately", "afternoon", "extremely", "version", "conflict", "forget", "achieve",
	"temperature", "majority", "relatively", "exercise", "customer", "approve", "survey", "mass", "male", "directly",
	"female", "clearly", "primary", "remove", "credit", "income", "grant", "restaurant", "serve", "title",
	"chief", "drink", "overall", "positive", "cool", "sample", "bus", "speed", "native", "prevent",
	"battle", "address", "largely", "option", "element", "mental", "judge", "construction", "domestic", "handle",
	"acquire", "moral", "observer", "volume", "decade", "chief", "failure", "speech", "assessment", "balance",
	"waste", "difficulty", "tradition", "separate", "respect", "examine", "touch", "rely", "weapon", "initial",
	"reform", "trip", "generally", "slightly", "publish", "lift", "attempt", "shift", "profit", "reform",
	"discover", "circle", "struggle", "literature", "destroy", "newspaper", "proportion", "provision", "strike", "crowd",
	"essential", "sector", "length", "seriously", "hate", "spirit", "quiet", "equipment", "violence", "favour",
	"labour", "honour", "neighbour", "travelling", "catalogue", "theatre", "metre", "litre", "fibre", "analyse",
	"apologise", "capitalise", "categorise", "characterise", "civilise", "colonise", "criticise", "customise", "emphasise", "energise",
	"equalise", "finalise", "generalise", "globalise", "harmonise", "hospitalise", "hypothesise", "idealise", "immunise", "initialise",
	"legalise", "liberalise", "localise", "materialise", "maximise", "memorise", "minimise", "modernise", "naturalise", "neutralise",
}

// GetRandomWords returns n random words from the common words list
// All words are converted to lowercase and empty words are skipped
func GetRandomWords(n int, rng func(int) int) []string {
	result := make([]string, 0, n)
	for len(result) < n {
		word := strings.ToLower(CommonWords[rng(len(CommonWords))])
		// Skip empty words or words with only spaces
		if len(strings.TrimSpace(word)) > 0 {
			result = append(result, word)
		}
	}
	return result
}
